cart/urls.py
from django.urls import path, include
from .views import all_dishes, add_to_cart, cart_list, delete_from_cart, delete_all
app_name = 'cart'

urlpatterns=[path('make_an_order/', all_dishes, name='make_an_order'),
             path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
             path('cart_list/', cart_list, name='cart_list'),
             path('delete_from_cart/<int:id>/', delete_from_cart, name='delete_from_cart'),
             path('delete_all/<int:id>/', delete_all, name='delete_all'),
             ]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls', namespace='my_app')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('order.urls', namespace='order')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# адреса представлений
#accounts/login/ [name='login']
#accounts/logout/ [name='logout']
#accounts/password_change/ [name='password_change']
#accounts/password_change/done/ [name='password_change_done']
#accounts/password_reset/ [name='password_reset']
#accounts/password_reset/done/ [name='password_reset_done']
#accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
#accounts/reset/done/ [name='password_reset_complete']

order/urls.py
from django.urls import path
from .views import make_an_order



app_name = 'order'

urlpatterns = [path('plase_an_order/', make_an_order, name ='plase_an_order'),
               ]

templates/cart_templates/dishes_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Блюда доступные для заказа</title>
</head>
<body>
<div>
{% if messages %}
    {% for message in messages %}
        {{ message.tags }} {{ message }}
    {% endfor %}
{% endif %}
</div>

<a style="margin-left: 85%" href="{% url 'cart:cart_list' %}" >Мой заказ</a>

<div>
    {% if dishes_list %}

    <h2>Блюда доступные для заказа</h2>
    <ul>
        {% for dish in dishes_list %}

        <li> Наименование блюда: {{dish.dish}} |
            Цена: {{dish.price}}| <a href="{% url 'cart:add_to_cart' dish.id %}">Добавить в заказ</a> </li>

        {% endfor %}
    </ul>
    {% else %}

    <h2>Нет доступных блюд</h2>

    {% endif %}
</div>


</body>
</html>

templates/cart_templates/in_cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Корзина</title>
</head>
<body>
<a href="{% url 'cart:make_an_order' %}">Вернуться на страницу выбора блюд</a>
<div>
    {% if messages %}
    {% for message in messages %}
    {{ message.tags }} {{ message }}
    {% endfor %}
    {% endif %}
</div>

<div>

    {% if in_cart %}

    <ul>

        {% for element in in_cart %}


        <li>Наименование: {{element.dish_name.dish}} - Количество: {{element.quantity}} шт. - Цена:
            {{element.position_total_price}} руб. | <a href="{% url 'cart:delete_from_cart' element.id %}">Удалить</a> |
            <a href="{% url 'cart:delete_all' element.id %}">Удалить все</a>
        </li>


        {% endfor %}
        <li>Количество блюд в заказе: {{res}}</li>
        <li>Общая стоимость: {{order_price}} руб.</li>

    </ul>

    <a href="{% url 'order:plase_an_order' %}">Оформить заказ</a>

    {% else %}

    <h2>Корзина пуста</h2>

    {% endif %}


</div>


</body>
</html>