cart/urls.py
from django.urls import path, include
from .views import all_dishes, add_to_cart, cart_list, delete_from_cart, delete_all
app_name = 'cart'

urlpatterns=[path('make_an_order/', all_dishes, name='make_an_order'),
             path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
             path('cart_list/', cart_list, name='cart_list'),
             path('delete_from_cart/<int:id>/', delete_from_cart, name='delete_from_cart'),
             path('delete_all/<int:id>/', delete_all, name='delete_all'),
             ]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls', namespace='my_app')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('order.urls', namespace='order')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# адреса представлений
#accounts/login/ [name='login']
#accounts/logout/ [name='logout']
#accounts/password_change/ [name='password_change']
#accounts/password_change/done/ [name='password_change_done']
#accounts/password_reset/ [name='password_reset']
#accounts/password_reset/done/ [name='password_reset_done']
#accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
#accounts/reset/done/ [name='password_reset_complete']

my_app/urls.py
from django.urls import path
from .views import my_view, create, edit, delete, main    # импорт представления


app_name = 'my_app'

urlpatterns = [path('', my_view, name='dish_form'),
               path('create/', create, name='create'),
               path('edit/<int:id>', edit, name='edit'),
               path('delete/<int:id>', delete, name='delete'),
               path('main/', main, name='main')]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Main page{% endblock title %}</title>
</head>
<body>

<h3>header</h3>

<div>
    {% block head %}
    <h1>Главная страница </h1>
    {% endblock %}
</div>

{% block content %}
<div>
    {% if user.is_authenticated %}
    <b>{{user.username}}</b> - В сети
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <a href="#" onclick="parentNode.submit();">Выход</a>
    </form>
    {% else %}
    <p>Для оформления заказа необходим вход в систему</p>

    <a href="{% url 'login' %}">Вход</a>
    {% endif %}
</div>

<div>

    <p><a href="{% url 'cart:make_an_order' %}">Меню</a></p>
    <p><a href="{% url 'my_app:dish_form' %}">Часть администратора</a></p>
    {% endblock %}

</div>


<h3>footer</h3>
</body>
</html>