cart/urls.py
from django.urls import path, include
from .views import all_dishes, add_to_cart, cart_list, delete_from_cart, delete_all
app_name = 'cart'

urlpatterns=[path('make_an_order/', all_dishes, name='make_an_order'),
             path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
             path('cart_list/', cart_list, name='cart_list'),
             path('delete_from_cart/<int:id>/', delete_from_cart, name='delete_from_cart'),
             path('delete_all/<int:id>/', delete_all, name='delete_all'),
             ]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls', namespace='my_app')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('order.urls', namespace='order')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# адреса представлений
#accounts/login/ [name='login']
#accounts/logout/ [name='logout']
#accounts/password_change/ [name='password_change']
#accounts/password_change/done/ [name='password_change_done']
#accounts/password_reset/ [name='password_reset']
#accounts/password_reset/done/ [name='password_reset_done']
#accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
#accounts/reset/done/ [name='password_reset_complete']

my_app/urls.py
from django.urls import path
from .views import my_view, create, edit, delete, main    # импорт представления


app_name = 'my_app'

urlpatterns = [path('', my_view, name='dish_form'),
               path('create/', create, name='create'),
               path('edit/<int:id>', edit, name='edit'),
               path('delete/<int:id>', delete, name='delete'),
               path('main/', main, name='main')]

templates/my_app_template/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Изменение значенйи в базе данных</title>
</head>

<body>
        <form method="post" action="{% url 'my_app:edit' order_model.id %}">
            {% csrf_token %}

             <p> <label>Блюдо: </label>
                 <input type="text" placeholder="Введите новое значение" name="dish">
             </p>

            <p> <label>Количество: </label>
                <input type="number" placeholder="Введите новое значение" name="quantity">
            </p>

            <p> <label>Цена: </label>
                <input type="number" placeholder="Введите новое значение" name="price">
            </p>

                <input type="submit" name="Изменить">

        </form>

</body>
</html>

templates/my_app_template/form_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Тестирую формы</title>
</head>
<body>

<div>

    <a href="{% url 'cart:make_an_order' %}" style="margin-left: 85%">Сделать заказ</a>

</div>
<div>
    <form method="post" action="{% url 'my_app:create' %}">
        {% csrf_token %}

        <p>
            <label>Наименование блюда</label>
            <input type="text" placeholder="Введите наименование блюда" name="dish">

        </p>

        <p>
            <label>Количество</label>
            <input type="number" placeholder="Введите количество" name="quantity">

        </p>

        <p>
            <label>Цена</label>
            <input type="number" placeholder="Введите цену" name="price">
        </p>

        <p>
            <input type="submit" value="Сохранить">
        </p>
    </form>

    {% if all_dishes %}

    <h2 style="margin-left: 20%">Блюда в базе данных</h2>

    <table>

        <thead align="center">
        <th width="15%">Наименование</th>
        <th width="10%">Количество</th>
        <th width="10%">Цена</th>
        </thead>
        {% for dish in all_dishes %}
        <tbody align="center">

        <td>{{dish.dish}}</td>

        <td>{{dish.quantity}}</td>

        <td>{{dish.total_price}}</td>
        <td><a href="{% url 'my_app:edit' dish.id %}">Изменить</a>|<a
                href="{% url 'my_app:delete' dish.id %}">Удалить</a></td>
        {% endfor %}

        </tbody>
    </table>

    {% else %}
    <h2 style="margin-left: 20%">Блюда в базе данных отсутствуют</h2>

    {% endif %}


</body>
</html>

templates/my_app_template/show_dishes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Мои блюда</title>
</head>
<body>
<div>
       <form method="post" action="{% url 'my_app:create' %}">
           {% csrf_token %}

           <p>
               <label>Наименование блюда</label>
                <input type="text" placeholder="Введите наименование блюда" name="dish">

           </p>

          <p>
              <label>Количество</label>
               <input type="number" placeholder="Введите количество" name="quantity">

          </p>

          <p>
              <label>Цена</label>
               <input type="number" placeholder="Введите цену" name="price">
          </p>

           <p>
               <input type="submit" value="Сохранить">
           </p>
       </form>

        {% for dish in all_dishes %}
            {{dish.dish}}
            {{dish.quantity}}
        {% endfor %}


</body>
</html>